version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login  --no-include-email --region us-west-2)
  build:
    commands:
      - echo Build started on 'date'
      - echo Building java
      - cd InternationalPatientTreatmentOfferings
      - mvn compile
      - mvn package
      - echo Building the Docker image..
      - docker build -t service/authmicro .
      - docker tag service/authmicro 130475542568.dkr.ecr.us-west-2.amazonaws.com/pod2-treatmentofferrepo:treatmentofferapp
      - echo "build ends.."
  post_build:
    commands:
    - echo Build completed on 'date'
    - echo Pushing the Docker image..
    - docker push 130475542568.dkr.ecr.us-west-2.amazonaws.com/pod2-treatmentofferrepo:treatmentofferapp
    - echo Writing definitions file
    - printf '[{"name":"pod2treatmentofferapp-container","imageUri":"%s"}]' 130475542568.dkr.ecr.us-west-2.amazonaws.com/pod2-treatmentofferrepo:treatmentofferapp > taskdefinition.json
     
artifacts:
  files:
    - InternationalPatientTreatmentOfferings/taskdefinition.json